services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: rag_ats
      POSTGRES_PASSWORD: rag_ats
      POSTGRES_DB: rag_ats
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
